name: Deploy DAGs to Astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy DAGs to Astro
        uses: astronomer/deploy-action@main
        with:
          astro-api-key: ${{ secrets.ASTRO_API_KEY }}
          deployment-id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
          action: deploy
