name: Deploy DAGs to Astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s

      - name: Authenticate with Astro
        run: |
          echo "${{ secrets.ASTRO_API_KEY }}" | astro login --token -

      - name: Deploy DAGs to Astro
        uses: astronomer/deploy-action@main
        with:
          deployment-id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
          action: deploy
