name: Deploy DAGs to Astro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash

      - name: Deploy DAGs to Astro
        uses: astronomer/deploy-action@v0.3
        with:
          deployment-id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
          api-token: ${{ secrets.ASTRO_API_TOKEN }}
          action: deploy
